backend:
  name: github
  repo: jeremymoreau/OCTcases
  branch: master

publish_mode: editorial_workflow
media_folder: "public/content/media"
public_folder: "/content/media"
logo_url: /assets/img/OCTcases-logo.svg 

collections:
  - name: "cases"
    label: "Cases"
    identifier_field: "caseID"
    extension: json
    folder: "public/content/cases"
    create: true
    slug: "{{slug}}"  # url-safe version of the post's title
    fields:
      - {label: "Case ID", name: "caseID", widget: "string", hint: "Unique Case ID (e.g. retina42). Must be different for each case.",  pattern: ["^[a-z]+[0-9]+$", "Format must be category+number, all lowercase with no spaces or symbols (e.g. retina42)"]}
      - {label: "Category", name: "category", widget: "select", options: ["retina", "neuro-ophthalmology", "uveitis", "glaucoma", "ocular oncology"]}
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,50}$", "Must be less than 50 characters"]}
      - {label: "Short Description", name: "description", widget: "string", pattern: ["^.{1,150}$", "Must be less than 150 characters"]}
      - {label: "Patient Presentation", name: "patientPresentation", widget: "markdown"}
      - label: "Questions"
        name: "questions"
        widget: "list"
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Question", name: "text", widget: "markdown"}
          - label: "Answers"
            name: "answers"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Answer", name: "answerText", widget: "string"}
              - {label: "Correct Answer?", name: "correct", widget: "boolean", default: false}
              - {label: "Explanation", name: "explanation", widget: "markdown", required: false, hint: "Explanation will only be displayed for correct answer"}
      - {label: "Footer", name: "footer", widget: "markdown", required: false, hint: "This content will be displayed below the questions (e.g. references, learning objectives)"}
  - name: "articles"
    label: "Articles"
    extension: json
    folder: "public/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,50}$", "Must be less than 50 characters"]}
      - {label: "Article", name: "article", widget: "markdown"}
  - name: "atlas"
    label: "Atlas"
    extension: json
    folder: "public/content/atlas" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,50}$", "Must be less than 50 characters"]}
      - {label: "Main Image", name: "mainImage", widget: "image", hint: "Image that will be displayed in Atlas gallery"}
      - {label: "Article", name: "article", widget: "markdown", required: false}
      - {label: "Case ID of linked practice case", name: "caseID", widget: "string", required: false, hint: "Unique Case ID (e.g. retina42) of practice case to link at bottom of article",  pattern: ["^[a-z]+[0-9]+$", "Format must be category+number, all lowercase with no spaces or symbols (e.g. retina42)"]}
