backend:
  name: github
  repo: jeremymoreau/OCTcases
  branch: master

publish_mode: editorial_workflow
media_folder: "public/content/media"
public_folder: "/content/media"
logo_url: /assets/img/octcases-logo-light-small.svg 

collections:
  - name: "cases"
    label: "Cases"
    identifier_field: "caseID"
    extension: json
    folder: "public/content/cases"
    create: true
    slug: "{{slug}}"  # url-safe version of the post's title
    fields:
      - {label: "Case ID", name: "caseID", widget: "string", hint: "Unique Case ID (e.g. retina42). Must be different for each case.",  pattern: ["^[a-z]+[0-9]+$", "Format must be category+number, all lowercase with no spaces or symbols (e.g. retina42)"]}
      - {label: "Category", name: "category", widget: "select", options: ["retina", "neuro-ophthalmology", "uveitis", "glaucoma", "ocular oncology"]}
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,80}$", "Must be less than 80 characters"]}
      - {label: "Short Description", name: "description", widget: "string", pattern: ["^.{1,150}$", "Must be less than 150 characters"]}
      - {label: "Patient Presentation", name: "patientPresentation", widget: "markdown"}
      - label: "Questions"
        name: "questions"
        widget: "list"
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Question", name: "text", widget: "markdown"}
          - label: "Answers"
            name: "answers"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Answer", name: "answerText", widget: "string"}
              - {label: "Correct Answer?", name: "correct", widget: "boolean", default: false}
              - {label: "Explanation", name: "explanation", widget: "markdown", required: false, hint: "Explanation will only be displayed for correct answer"}
      - {label: "Footer", name: "footer", widget: "markdown", required: false, hint: "This content will be displayed below the questions (e.g. references, learning objectives)"}
  - name: "articles"
    label: "Articles"
    extension: json
    folder: "public/content/articles"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['sortOrder', 'title', 'commit_author', 'commit_date']
    fields:
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,80}$", "Must be less than 80 characters"]}
      - {label: "Short Description", name: "description", widget: "string", pattern: ["^.{1,150}$", "Must be less than 150 characters"]}
      - {label: "Sort Order", name: "sortOrder", widget: "number", min: 1, value_type: "int", hint: "Sort order (articles will be displayed in ascending order based on this value)"}
      - {label: "Article", name: "article", widget: "markdown"}
      - label: "Review Questions"
        name: "questions"
        widget: "list"
        allow_add: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Question", name: "text", widget: "markdown"}
          - label: "Answers"
            name: "answers"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Answer", name: "answerText", widget: "string"}
              - {label: "Correct Answer?", name: "correct", widget: "boolean", default: false}
              - {label: "Explanation", name: "explanation", widget: "markdown", required: false, hint: "Explanation will only be displayed for correct answer"}
      - {label: "Footer", name: "footer", widget: "markdown", required: false, hint: "This content will be displayed below the review questions (e.g. references, learning objectives)"}
  - name: "atlas"
    label: "Atlas"
    extension: json
    folder: "public/content/atlas" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,80}$", "Must be less than 80 characters"]}
      - {label: "Main Image", name: "mainImage", widget: "image", hint: "Image that will be displayed in Atlas gallery"}
      - {label: "Short Description", name: "description", widget: "text", pattern: ["^.{1,280}$", "Must be less than 280 characters"]}
      - {label: "Article", name: "article", widget: "markdown", required: false}
      - {label: "Case ID of linked practice cases", name: "caseID", widget: "string", required: false, hint: "Unique Case IDs of practice cases to link at bottom of article. Separate Case IDs with a comma (e.g. retina42,retina43) to include multiple cases.",  pattern: ["^([a-z]+[0-9]+,?)+$", "Format must be category+number, all lowercase with no spaces or symbols (e.g. retina42). Separate cases with a comma, no spaces"]}
      - {label: "Footer", name: "footer", widget: "markdown", required: false, hint: "This content will be displayed below the related practice cases."}
  - name: "pages"
    label: "Pages"
    identifier_field: "pageID"
    extension: json
    folder: "public/content/pages"
    create: false
    slug: "{{slug}}"  # url-safe version of the post's title
    fields:
      - {label: "Page ID", name: "pageID", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,80}$", "Must be less than 80 characters"]}
      - {label: "Page Content", name: "pageContent", widget: "markdown"}
  - name: "about-us"
    label: "About Us"
    identifier_field: "pageID"
    extension: json
    folder: "public/content/other/about-us"
    create: false
    slug: "{{slug}}"  # url-safe version of the post's title
    fields:
      - {label: "Page ID", name: "pageID", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,80}$", "Must be less than 80 characters"]}
      - {label: "Header", name: "pageHeader", widget: "markdown"}
      - label: "Groups"
        name: "groups"
        widget: "list"
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Person"
            name: "person"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image", required: false}
              - {label: "Subtitle line 1", name: "subtitle1", widget: "string"}
              - {label: "Subtitle line 2", name: "subtitle2", widget: "string"}
      - {label: "Footer", name: "pageFooter", widget: "markdown"}