backend:
  name: github
  repo: jeremymoreau/OCTcases
  branch: master

publish_mode: editorial_workflow
media_folder: "public/content/media"
public_folder: "/content/media"
logo_url: /assets/OCTcases-logo.svg 

collections:
  - name: "cases"
    label: "Cases"
    identifier_field: CaseID
    extension: json
    folder: "public/content/cases"
    create: true
    slug: "{{slug}}"  # url-safe version of the post's title
    fields:
      - {label: "Case ID", name: "caseID", widget: "string", pattern: ["^[a-z]+[0-9]+$", "Format must be category+number, all lowercase with no spaces or symbols (e.g. retina42)"]}
      - {label: "Category", name: "category", widget: "string", pattern: ["^[a-z]+$", "All lowercase with no spaces or symbols"]}
      - {label: "Title", name: "title", widget: "string", pattern: ["^.{1,50}$", "Must be less than 50 characters"]}
      - {label: "Description", name: "description", widget: "string", pattern: ["^.{1,150}$", "Must be less than 150 characters"]}